server:
  port: 9000

spring:
  sql:
    init:
      schema-locations: classpath*:db/WheelieSchema.sql
      username: root
      password: UwAp!d!5
      mode: always
      platform: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pedalers_wheelie?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true
    username: root
    password: flatron123!

    hikari:
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
